name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "
            cd ~/fastapi-trade-api &&
            git pull &&
            sudo docker stop \$(sudo docker ps -aq) &&
            sudo docker rm \$(sudo docker ps -aq) &&
            sudo docker build -t fastapi-trade-api . &&
            sudo docker run -d -p 80:8000 fastapi-trade-api
          "
